version: '3.8'

services:
  db:
    image: mysql:8.3.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: Sistema_Bibliotecario
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - dados_mysql:/var/lib/mysql

volumes:
  dados_mysql:
