// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sistema_bibliotecario_api.Data;

#nullable disable

namespace sistema_bibliotecario_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("sistema_bibliotecario_api.Models.Autor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Autores");
                });

            modelBuilder.Entity("sistema_bibliotecario_api.Models.Emprestimo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataDevolucaoPresvista")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataDevolucaoReal")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataEmprestimo")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Devolvido")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Livro_id")
                        .HasColumnType("int");

                    b.Property<int>("Usuario_id")
                        .HasColumnType("int");

                    b.Property<int?>("usuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Livro_id");

                    b.HasIndex("usuarioId");

                    b.ToTable("Emprestimos");
                });

            modelBuilder.Entity("sistema_bibliotecario_api.Models.Livro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AnoPublicado")
                        .HasColumnType("int");

                    b.Property<int>("Autor_id")
                        .HasColumnType("int");

                    b.Property<string>("Genero")
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Autor_id");

                    b.ToTable("Livros");
                });

            modelBuilder.Entity("sistema_bibliotecario_api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("sistema_bibliotecario_api.Models.Emprestimo", b =>
                {
                    b.HasOne("sistema_bibliotecario_api.Models.Livro", "Livro")
                        .WithMany()
                        .HasForeignKey("Livro_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sistema_bibliotecario_api.Models.Usuario", "usuario")
                        .WithMany("Emprestimos")
                        .HasForeignKey("usuarioId");

                    b.Navigation("Livro");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("sistema_bibliotecario_api.Models.Livro", b =>
                {
                    b.HasOne("sistema_bibliotecario_api.Models.Autor", "Autor")
                        .WithMany("Livros")
                        .HasForeignKey("Autor_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("sistema_bibliotecario_api.Models.Autor", b =>
                {
                    b.Navigation("Livros");
                });

            modelBuilder.Entity("sistema_bibliotecario_api.Models.Usuario", b =>
                {
                    b.Navigation("Emprestimos");
                });
#pragma warning restore 612, 618
        }
    }
}
